export { default as Header } from './Header/Header' 
export { default as Home } from './Home/Home' 
export { default as About } from './About/About' 
export { default as Comic } from './Comic/Comic' 
export { default as Lab } from './Lab/Lab' 
export { default as Shop } from './Shop/Shop' 
export {default as Navbar} from './Navbar/Navbar'
export {default as Explore} from './Explore/Explore'
export {default as Meet} from './Meet/Meet'
export {default as News} from './News/New'